
BINARY_NAME = strategy_app


all: run

run:
	@echo "A executar o padrão Strategy em Go..."
	@go run *.go

build:
	@echo "A compilar o executável..."
	@go build -o $(BINARY_NAME) *.go


clean:
	@echo "A limpar o executável..."
	@rm -f $(BINARY_NAME)